[profile.default]
slow-timeout = { period = "60s", terminate-after = 2 }
retries = 1
failure-output = "immediate"

[profile.ci]
slow-timeout = { period = "120s", terminate-after = 2 }
retries = 2
run-ignored = "failure"
fail-fast = true
